version: '3.2'

services:
    python:
    image: ex21/python:1.0
    build: ./python
    container_name: 'ex21_python'
    working_dir: '/tmp/work'
    volumes:
      - ../python:/tmp/work
    stdin_open: true
    tty: true